#!/usr/bin/env bash
# shellcheck disable=SC2009
for pid in /proc/[0-9]*; do
    pid=${pid##*/}
    if grep -q bash "/proc/$pid/comm" 2>/dev/null; then
        echo "$pid $(cat "/proc/$pid/comm")"
    fi
done
