#!/usr/bin/env bash
# This script handles SIGTERM and runs forever

echo $$ > /tmp/myscript.pid

trap 'echo "I hate the kill command"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
