#!/usr/bin/env bash

# This script runs indefinitely and writes a message to a file every 2 seconds

while true
do
    echo "I am alive!" >> /tmp/my_process   # Append message to file
    sleep 2                                 # Wait for 2 seconds
done
