#!/usr/bin/env bash
# This script manages the manage_my_process program

case "$1" in
    start)
        ./manage_my_process &
        echo $! > /tmp/my_process.pid
        echo "manage_my_process started"
        ;;
